### ISSUE TITLE
Color Picker Filtering Improvements 

### ISSUE THREAD

**Issue by danielhickman** [WirelessBytes/materialcolorize#20]
- [x] Force footer to bottom 
- [x] Extra headers and All Colors header to the set that's picked
- [x] Extra headers (and extra divider on black) appear when using Format then Color
- [x] Add a "none" card for no results
- [ ] Make color switcher check for displayed or use the set variable for displaying and none card

**Comment by crutchcorn** [comment]
https://forum.jquery.com/topic/picking-a-color-from-an-image
http://home.jejaju.com/play/colorpicker
http://baijs.com/tinycolorpicker/
https://github.com/wieringen/tinycolorpicker
http://www.script-tutorials.com/creating-an-html5-canvas-image-color-picker/
Don't mind me

**Comment by danielhickman** [comment]
Closed for Polymer
