### ISSUE TITLE
PHP Redo of JS Color Picker

### ISSUE THREAD

**Issue by danielhickman** [WirelessBytes/materialcolorize#31]
Use PHP instead of JS for the color picker this should fix the following issues:  #20 #27 #30

**Comment by crutchcorn** [comment]
Why not a... JHP... ;D ;D ;D ;D ;D ;D ;D Eh? Eh?

**Comment by danielhickman** [comment]
A da what now?

**Comment by crutchcorn** [comment]
RHP... Your other project?

**Comment by danielhickman** [comment]
Ah yes. That project willttake a while.

**Comment by crutchcorn** [comment]
I know, I know. :P

**Comment by danielhickman** [comment]
Closed for Polymer
