### ISSUE TITLE
Convert Colors Does Not Stop You After 6/7 (depending on #) Letters

### ISSUE THREAD

**Issue by crutchcorn** [WirelessBytes/materialcolorize#32]
This should do so as the default #FFFFFF is all that you'd need

**Comment by danielhickman** [comment]
It shouldn't stop, but it only used #fff or #fff with or without the pound
symbol.

**Comment by crutchcorn** [comment]
What do you mean it shouldn't stop? Idealy, we'd have a picker to change the input method

**Comment by danielhickman** [comment]
Yeah a picker and a better text imput

**Comment by danielhickman** [comment]
Closed for Polymer
